# Generated by Django 2.1.4 on 2019-01-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('date', models.DateTimeField(null=True)),
                ('duree', models.DurationField(null=True)),
                ('gallerie', models.FilePathField(null=True, path='/media/photos')),
                ('description', models.TextField()),
            ],
        ),
    ]
