# Generated by Django 2.1.4 on 2019-01-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='duree',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='gallerie',
            field=models.FilePathField(blank=True, null=True, path='/media/photos'),
        ),
    ]
