# Generated by Django 2.1.4 on 2019-01-20 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190120_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='duree',
        ),
        migrations.AddField(
            model_name='event',
            name='debut',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
