# Generated by Django 2.1.4 on 2019-02-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20190201_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gallerie',
            field=models.FilePathField(allow_folders=True, blank=True, null=True, path='/media/'),
        ),
    ]
