# Generated by Django 2.1.4 on 2019-03-31 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20190201_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='gallerie',
        ),
    ]
