# Generated by Django 2.1.4 on 2019-04-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_event_gallerie'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gallerie',
            field=models.FilePathField(allow_folders=True, blank=True, null=True, path='media/'),
        ),
    ]
