# Generated by Django 2.1.4 on 2019-04-01 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_gallerie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='gallerie',
        ),
    ]
