# Generated by Django 2.1.4 on 2019-02-08 09:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotline',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 8, 9, 48, 52, 340677, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hotline',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotline',
            name='delivery_time',
            field=models.TimeField(),
        ),
    ]
