# Generated by Django 2.1.4 on 2019-02-09 22:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0002_auto_20190208_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotline',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 9, 22, 7, 34, 981125, tzinfo=utc)),
        ),
    ]
