# Generated by Django 2.1.4 on 2019-02-11 13:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotline', '0003_auto_20190209_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crepes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_time', models.TimeField()),
                ('delivery_date', models.DateField(default=datetime.datetime(2019, 2, 11, 13, 35, 7, 220392, tzinfo=utc))),
                ('delivery_place', models.CharField(max_length=500)),
                ('comment', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('garniture', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='hotline',
            name='user',
        ),
        migrations.DeleteModel(
            name='Hotline',
        ),
    ]
