# Generated by Django 2.1.4 on 2019-02-18 09:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0004_auto_20190211_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='crepes',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crepes',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 18, 9, 26, 39, 529115, tzinfo=utc)),
        ),
    ]
