# Generated by Django 2.1.4 on 2019-02-19 18:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0006_auto_20190218_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crepes',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 19, 18, 5, 43, 215596, tzinfo=utc)),
        ),
    ]
