# Generated by Django 2.1.4 on 2019-02-21 21:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0007_auto_20190219_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='crepes',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crepes',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 21, 21, 22, 20, 371355, tzinfo=utc)),
        ),
    ]
