# Generated by Django 2.1.4 on 2019-02-21 21:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0008_auto_20190221_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crepes',
            name='delivered',
        ),
        migrations.AlterField(
            model_name='crepes',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 21, 21, 32, 26, 530948, tzinfo=utc)),
        ),
    ]
