# Generated by Django 2.1.4 on 2019-02-25 21:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0010_auto_20190225_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apero',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 25, 21, 59, 52, 214439, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='crepes',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 25, 21, 59, 52, 214439, tzinfo=utc)),
        ),
    ]
