# Generated by Django 2.1.4 on 2019-03-04 08:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0012_auto_20190304_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apero',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 4, 8, 49, 26, 824279, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='crepes',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 4, 8, 49, 26, 824279, tzinfo=utc)),
        ),
    ]
