# Generated by Django 2.1.4 on 2019-03-25 14:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotline', '0014_auto_20190304_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetitDej',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_time', models.TimeField()),
                ('delivery_date', models.DateField(default=datetime.datetime(2019, 3, 25, 14, 14, 10, 593970, tzinfo=utc))),
                ('delivery_place', models.CharField(max_length=500)),
                ('comment', models.TextField(blank=True, null=True)),
                ('gout_muffin', models.CharField(max_length=500)),
                ('compote', models.CharField(max_length=300)),
                ('quatre_quart', models.BooleanField(default=True)),
                ('boisson_chaude', models.CharField(max_length=500)),
                ('jus', models.CharField(max_length=500)),
                ('tartine', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='apero',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 14, 14, 10, 593970, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='crepes',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 14, 14, 10, 593970, tzinfo=utc)),
        ),
    ]
