# Generated by Django 2.1.4 on 2019-03-26 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0017_auto_20190326_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='apero',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crepes',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='muffin',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petitdej',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apero',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 26, 18, 20, 25, 740233, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='crepes',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 26, 18, 20, 25, 740233, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='muffin',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 26, 18, 20, 25, 740233, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='petitdej',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 26, 18, 20, 25, 740233, tzinfo=utc)),
        ),
    ]
