# Generated by Django 2.1.4 on 2019-03-26 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0018_auto_20190326_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apero',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='crepes',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='muffin',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='petitdej',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
