# Generated by Django 2.1.4 on 2019-03-27 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0019_auto_20190326_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crepes',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='apero',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(1)]),
        ),
    ]
