# Generated by Django 2.1.4 on 2019-04-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0022_auto_20190327_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apero',
            name='delivery_place',
            field=models.CharField(default='Meuh', max_length=500),
        ),
        migrations.AlterField(
            model_name='crepes',
            name='delivery_place',
            field=models.CharField(default='Meuh', max_length=500),
        ),
        migrations.AlterField(
            model_name='muffin',
            name='delivery_place',
            field=models.CharField(default='Meuh', max_length=500),
        ),
        migrations.AlterField(
            model_name='petitdej',
            name='delivery_place',
            field=models.CharField(default='Meuh', max_length=500),
        ),
    ]
