# Generated by Django 2.1.4 on 2019-04-04 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0024_auto_20190402_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='crepes',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
