# Generated by Django 2.1.4 on 2019-04-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0025_crepes_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crepes',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='petitdej',
            name='boisson_chaude',
            field=models.CharField(default='rien', max_length=500),
        ),
        migrations.AlterField(
            model_name='petitdej',
            name='compote',
            field=models.CharField(default='rien', max_length=300),
        ),
        migrations.AlterField(
            model_name='petitdej',
            name='gout_muffin',
            field=models.CharField(default='rien', max_length=500),
        ),
        migrations.AlterField(
            model_name='petitdej',
            name='jus',
            field=models.CharField(default='rien', max_length=500),
        ),
        migrations.AlterField(
            model_name='petitdej',
            name='tartine',
            field=models.CharField(default='rien', max_length=500),
        ),
    ]
