# Generated by Django 2.1.4 on 2019-01-28 14:10

from django.db import migrations, models
import team.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listeux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('poste', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to=team.models.rename)),
            ],
        ),
    ]
