# Generated by Django 2.1.4 on 2019-03-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190119_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='message'),
        ),
    ]
