# Generated by Django 2.1.4 on 2019-03-29 20:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190304_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 29, 20, 30, 13, 347401, tzinfo=utc), verbose_name='date published'),
        ),
    ]
