# Generated by Django 2.1.4 on 2019-03-30 15:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190329_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 30, 15, 7, 53, 609060, tzinfo=utc), verbose_name='date published'),
        ),
    ]
