# Generated by Django 2.1.4 on 2019-03-31 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190330_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 31, 13, 9, 58, 216107, tzinfo=utc), verbose_name='date published'),
        ),
    ]
