# Generated by Django 2.1.4 on 2019-04-01 00:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20190331_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 1, 0, 16, 0, 668227, tzinfo=utc), verbose_name='date published'),
        ),
    ]
