# Generated by Django 2.1.4 on 2019-04-01 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20190401_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 1, 14, 29, 22, 996939, tzinfo=utc), verbose_name='date published'),
        ),
    ]
