# Generated by Django 2.1.4 on 2019-04-01 17:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20190401_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 1, 17, 40, 44, 194049, tzinfo=utc), verbose_name='date published'),
        ),
    ]
