# Generated by Django 2.1.4 on 2019-04-02 00:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20190401_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 2, 0, 1, 56, 443732, tzinfo=utc), verbose_name='date published'),
        ),
    ]
