# Generated by Django 2.1.4 on 2019-04-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20190402_1320'),
        ('polls', '0024_auto_20190402_1238'),
    ]

    operations = [
    ]
