# Generated by Django 2.1.4 on 2019-04-03 14:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_merge_20190402_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 3, 14, 23, 19, 264702, tzinfo=utc), verbose_name='date published'),
        ),
    ]
