# Generated by Django 2.1.4 on 2019-04-03 18:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20190403_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 3, 18, 48, 38, 23189, tzinfo=utc), verbose_name='date published'),
        ),
    ]
