# Generated by Django 2.1.4 on 2019-04-04 07:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_auto_20190403_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 4, 7, 24, 29, 969410, tzinfo=utc), verbose_name='date published'),
        ),
    ]
