# Generated by Django 2.1.4 on 2019-04-06 12:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20190404_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 6, 12, 14, 15, 642234, tzinfo=utc), verbose_name='date published'),
        ),
    ]
