# Generated by Django 2.1.4 on 2019-03-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0002_auto_20190219_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesure',
            name='description',
        ),
        migrations.AddField(
            model_name='mesure',
            name='concret',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mesure',
            name='constat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mesure',
            name='preambule',
            field=models.TextField(null=True),
        ),
    ]
